name: Auto Commit

on:
  schedule:
    - cron: '0 23 * * 1-6'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run auto-commit script
      run: /bin/bash auto-commit.sh
